### ISSUE TITLE
error: "not" cannot be used as a macro name as it is an operator in C++

### ISSUE THREAD

**Issue by BADAL244** [rickytan/iSAM#1]
/home/badal/iSAM/isamlib/Optimizer.cpp:39:9: error: "not" cannot be used as a macro name as it is an operator in C++
   39 | #define not !
      |         ^~~
make[2]: *** [isamlib/CMakeFiles/isamlib.dir/build.make:141: isamlib/CMakeFiles/isamlib.dir/Optimizer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:165: isamlib/CMakeFiles/isamlib.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by rickytan** [comment]
This is a old project, it may only compile with C++11

**Comment by rickytan** [comment]
Or, you can replace `not` to `NOT`
